# Handling Errors with try/except

```python
def div42by(num):
    try:
        return 42 / num
    except ZeroDivisionError:
        print("Error: dividiste por 0 mas atento la proxima")
```

Programa super simple de adivina el numero

![](../../.gitbook/assets/imagen%20%28928%29.png)



